INSERT INTO `Ubiq`.`Evenement` (`nom`, `description`, `prix`, `typeEvenement`) VALUES
( 'John Smith', 'Experienced chauffeur for VIP events', 500.0, 'chauffeur'),
( 'Sarah Jones', 'Expert driver with extensive experience in VIP transportation', 600.0, 'chauffeur'),
( 'David Lee', 'Professional driver with luxury car for VIP transportation', 700.0, 'chauffeur'),
('Emily Chen', 'Chauffeur with impeccable driving record for high-profile clients', 550.0, 'chauffeur'),
('Michael Brown', 'Experienced driver with top-notch customer service skills', 650.0, 'chauffeur'),
('Karen Kim', 'Chauffeur with excellent knowledge of local roads and traffic patterns', 600.0, 'chauffeur'),
( 'Chris Evans', 'Professional driver with luxury car for high-profile clients', 750.0, 'chauffeur'),
('Linda Nguyen', 'Experienced driver with excellent communication skills', 550.0, 'chauffeur'),
( 'Ryan Patel', 'Chauffeur with impeccable safety record for VIP events', 600.0, 'chauffeur'),
('Amy Liu', 'Expert driver with top-of-the-line luxury car for high-profile clients', 800.0, 'chauffeur'),
('Cozy Cabin', 'A quaint and cozy cabin in the woods', 100.0, 'chalet'),
('Mountain Chalet', 'A luxurious chalet with stunning mountain views', 250.0, 'chalet'),
('Rustic Retreat', 'A rustic retreat perfect for a weekend getaway', 150.0, 'chalet'),
('Lakeside Lodge', 'A spacious lodge with breathtaking views of the lake', 300.0, 'chalet'),
('Ski-in/Ski-out Chalet', 'A cozy chalet just steps away from the ski slopes', 200.0, 'chalet'),
('Treehouse Getaway', 'A unique and cozy treehouse in the forest', 125.0, 'chalet'),
('Secluded Cabin', 'A secluded cabin with a hot tub and fireplace', 175.0, 'chalet'),
('Luxury Chalet', 'A luxurious chalet with all the amenities', 400.0, 'chalet'),
('Modern Mountain Retreat', 'A modern and stylish mountain retreat', 225.0, 'chalet'),
( 'Family-Friendly Chalet', 'A spacious and family-friendly chalet in the woods', 175.0, 'chalet'),
('Hiking in the Mountains', 'Explore the beautiful mountain scenery on foot', 50.0, 'pleinAir'),
( 'Camping in the Woods', 'Experience the great outdoors with a camping trip', 75.0, 'pleinAir'),
( 'Kayaking Adventure', 'Paddle through scenic rivers and lakes on a kayaking adventure', 100.0, 'pleinAir'),
( 'Whitewater Rafting', 'Experience the rush of adrenaline with whitewater rafting', 150.0, 'pleinAir'),
( 'Zip Line Adventure', 'Soar through the treetops on a thrilling zip line adventure', 75.0, 'pleinAir'),
('Italian Restaurant', 'Enjoy authentic Italian cuisine in a cozy atmosphere', 50.0, 'restauration'),
('Seafood Restaurant', 'Savor the taste of the ocean with fresh seafood dishes', 7.0, 'restauration'),
('Steakhouse', 'Indulge in a juicy steak cooked to perfection', 100.0, 'restauration'),
('Sushi Bar', 'Experience the art of sushi making with a variety of rolls', 150.0, 'restauration'),
('Mexican Restaurant', 'Enjoy flavorful Mexican dishes with a margarita on the side', 75.0, 'restauration'),
('Burger Joint', 'Sink your teeth into a delicious burger with all the fixings', 80.0, 'restauration'),
('Brunch Spot', 'Start your day off right with a delicious brunch', 50.0, 'restauration'),
('Asian Fusion', 'Experience the fusion of flavors from different Asian cuisines', 100.0, 'restauration'),
('Gourmet Dining', 'Indulge in a gourmet dining experience with exquisite dishes and wine pairings', 200.0, 'restauration'),
('Vegan Restaurant', 'Enjoy delicious plant-based dishes that are good for you and the planet', 75.0, 'restauration'),
('Wine Tasting Tour', 'Discover the flavors of the region with a guided wine tasting tour', 75.0, 'routeVin'),
('Vineyard Walk', 'Take a leisurely stroll through the vineyards and learn about the wine-making process', 50.0, 'routeVin'),
('Wine and Cheese Pairing', 'Savor the perfect pairing of wine and cheese with a guided tasting', 100.0, 'routeVin'),
('Cellar Tour', 'Explore the underground cellars where the wine is aged to perfection', 75.0, 'routeVin'),
('Grape Harvest', 'Join in the grape harvest and experience the hard work that goes into making wine', 150.0, 'routeVin'),
('Wine Museum Visit', 'Learn about the history of wine-making with a visit to the local wine museum', 50.0, 'routeVin'),
('Wine and Food Pairing', 'Enjoy a multi-course meal paired perfectly with local wines', 200.0, 'routeVin'),
('Wine Festival', 'Celebrate the harvest season with a wine festival featuring local wineries and food vendors', 75.0, 'routeVin'),
('Wine Country Bike Tour', 'Explore the wine country on two wheels with a guided bike tour', 100.0, 'routeVin'),
('Wine Tasting Workshop', 'Learn how to taste wine like a pro with a hands-on workshop', 80.0, 'routeVin');

 